server:
  port: 8084

spring:
  application:
    name: order-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ticketdb}
    username: ${SPRING_DATASOURCE_USERNAME:ticketuser}
    password: ${SPRING_DATASOURCE_PASSWORD:ticketpass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    defer-datasource-initialization: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
# Service
service:
  event:
    url: ${EVENT_SERVICE_URL:http://localhost:8082/api/v1/tickets}
  user:
    url: ${USER_SERVICE_URL:http://localhost:8081}